// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvqemkipixrvfmqwfgdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cWVta2lwaXhydmZtcXdmZ2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTIzMTQsImV4cCI6MjA3MTk2ODMxNH0.VtYliBtd2HDGsbbsZQunhk4PB-TJFJEq25i2b3j-5q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});